public let WINMUX_WINDOW_ID = "WINMUX_WINDOW_ID"
public let WINMUX_WORKSPACE = "WINMUX_WORKSPACE"
public let WINMUX_FOCUSED_WORKSPACE = "WINMUX_FOCUSED_WORKSPACE"
public let WINMUX_PREV_WORKSPACE = "WINMUX_PREV_WORKSPACE"
