VERSION ?= 0.0.0-SNAPSHOT
CODESIGN_IDENTITY ?= Apple Development
DEVELOPMENT_TEAM ?= W9C2P3N7Q2
RELEASE_DIR ?= .release
RELEASE_TAG ?= v$(VERSION)
RELEASE_NOTES ?= auto
PUBLISH ?= 1
ARGS ?=

.PHONY: generate xcodeproj build build-clean run run-clean cli release clean

generate:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let winMuxAppVersion = \"$(VERSION)\"" > Sources/Common/versionGenerated.swift && \
	git_hash="$$(git rev-parse HEAD 2>/dev/null || echo SNAPSHOT)"; \
	git_short_hash="$$(git rev-parse --short HEAD 2>/dev/null || echo SNAPSHOT)"; \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let gitHash = \"$$git_hash\"" "public let gitShortHash = \"$$git_short_hash\"" > Sources/Common/gitHashGenerated.swift'

xcodeproj:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	export XCODEGEN_WINMUX_VERSION="$(VERSION)" && \
	export XCODEGEN_WINMUX_CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" && \
	export XCODEGEN_WINMUX_DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" && \
	./script/install-dep.sh --xcodegen && \
	./.deps/xcodegen/xcodegen'

build:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	swift build && \
	swift build --target AppBundleTests && \
	rm -rf .debug && \
	mkdir .debug && \
	cp -r .build/debug/winmux .debug && \
	cp -r .build/debug/WinMuxApp .debug'

build-clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug'
	$(MAKE) build VERSION="$(VERSION)"

run:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	if [ -n "$${AEROSPACE_CONFIG_PATH:-}" ]; then \
	    if [ ! -f "$$AEROSPACE_CONFIG_PATH" ]; then \
	        echo "Missing WinMux config: $$AEROSPACE_CONFIG_PATH" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$AEROSPACE_CONFIG_PATH" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

run-clean:
	$(MAKE) build-clean VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	if [ -n "$${AEROSPACE_CONFIG_PATH:-}" ]; then \
	    if [ ! -f "$$AEROSPACE_CONFIG_PATH" ]; then \
	        echo "Missing WinMux config: $$AEROSPACE_CONFIG_PATH" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$AEROSPACE_CONFIG_PATH" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

cli:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && exec ./.debug/winmux $(ARGS)'

release:
	$(MAKE) xcodeproj VERSION="$(VERSION)" CODESIGN_IDENTITY="$(CODESIGN_IDENTITY)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	set -euo pipefail && \
	source ./script/setup.sh && \
	test -n "$(VERSION)" && \
	app_name="WinMux"; \
	release_dir="$(RELEASE_DIR)"; \
	archive_path="$$release_dir/$$app_name-$(VERSION).xcarchive"; \
	app_path="$$archive_path/Products/Applications/$$app_name.app"; \
	zip_path="$$release_dir/$$app_name-$(VERSION).zip"; \
	log_path="$$release_dir/$$app_name-$(VERSION)-xcodebuild.log"; \
	rm -rf "$$archive_path" "$$zip_path"; \
	mkdir -p "$$release_dir"; \
	xcodebuild-pretty "$$log_path" \
	    -project WinMux.xcodeproj \
	    -scheme WinMux \
	    -configuration Release \
	    -archivePath "$$archive_path" \
	    CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" \
	    DEVELOPMENT_TEAM="$(DEVELOPMENT_TEAM)" \
	    CODE_SIGN_STYLE=Automatic \
	    archive; \
	test -d "$$app_path"; \
	codesign --verify --deep --strict --verbose=2 "$$app_path"; \
	ditto -c -k --sequesterRsrc --keepParent "$$app_path" "$$zip_path"; \
	if [ "$(PUBLISH)" != "1" ]; then \
	    echo "Skipping GitHub release publish because PUBLISH=$(PUBLISH)"; \
	elif /usr/bin/which gh >/dev/null 2>&1; then \
	    if gh release view "$(RELEASE_TAG)" >/dev/null 2>&1; then \
	        gh release upload "$(RELEASE_TAG)" "$$zip_path" --clobber; \
	    else \
	        if [ "$(RELEASE_NOTES)" = "auto" ]; then \
	            gh release create "$(RELEASE_TAG)" "$$zip_path" --title "$$app_name $(VERSION)" --generate-notes; \
	        else \
	            gh release create "$(RELEASE_TAG)" "$$zip_path" --title "$$app_name $(VERSION)" --notes "$(RELEASE_NOTES)"; \
	        fi; \
	    fi; \
	else \
	    echo "warning: gh is not installed; built $$zip_path but did not publish a GitHub release" >&2; \
	fi'

clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug .deps .derived "$(RELEASE_DIR)" WinMux.xcodeproj'
