VERSION ?= 0.0.0-SNAPSHOT
CODESIGN_IDENTITY ?= winmux-codesign-certificate
ARGS ?=

.PHONY: generate xcodeproj build run cli clean

generate:
	/bin/bash -lc 'cd "$(CURDIR)" && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let winMuxAppVersion = \"$(VERSION)\"" > Sources/Common/versionGenerated.swift && \
	printf "%s\n" "// FILE IS GENERATED BY Makefile" "public let gitHash = \"SNAPSHOT\"" "public let gitShortHash = \"SNAPSHOT\"" > Sources/Common/gitHashGenerated.swift'

xcodeproj:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	export XCODEGEN_WINMUX_VERSION="$(VERSION)" && \
	export XCODEGEN_WINMUX_CODE_SIGN_IDENTITY="$(CODESIGN_IDENTITY)" && \
	./script/install-dep.sh --xcodegen && \
	./.deps/xcodegen/xcodegen'

build:
	$(MAKE) generate VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	source ./script/setup.sh && \
	swift build && \
	swift build --target AppBundleTests && \
	rm -rf .debug && \
	mkdir .debug && \
	cp -r .build/debug/winmux .debug && \
	cp -r .build/debug/WinMuxApp .debug'

run:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && \
	if pgrep -x yabai >/dev/null 2>&1; then echo "warning: yabai is still running and may conflict with WinMux" >&2; fi && \
	if pgrep -x skhd >/dev/null 2>&1; then echo "warning: skhd is still running; its yabai shortcuts will keep firing" >&2; fi && \
	if [ -n "$${AEROSPACE_CONFIG_PATH:-}" ]; then \
	    if [ ! -f "$$AEROSPACE_CONFIG_PATH" ]; then \
	        echo "Missing WinMux config: $$AEROSPACE_CONFIG_PATH" >&2; \
	        exit 1; \
	    fi; \
	    exec ./.debug/WinMuxApp --config-path "$$AEROSPACE_CONFIG_PATH" $(ARGS); \
	else \
	    exec ./.debug/WinMuxApp $(ARGS); \
	fi'

cli:
	$(MAKE) build VERSION="$(VERSION)"
	/bin/bash -lc 'cd "$(CURDIR)" && exec ./.debug/winmux $(ARGS)'

clean:
	/bin/bash -lc 'cd "$(CURDIR)" && rm -rf .build .debug .deps WinMux.xcodeproj'
