config-version = 2

start-at-login = false
auto-reload-config = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30

window-tabs.enabled = true
window-tabs.height = 34

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

automatically-unhide-macos-hidden-apps = false
enable-window-management = true
shortcuts-preset = 'none'
persistent-workspaces = []
on-mode-changed = []

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 8
    inner.vertical = 8
    outer.left = 8
    outer.bottom = 8
    outer.top = 8
    outer.right = 8

[workspace-sidebar]
    enabled = true
    collapsed-width = 44
    width = 240
    monitor = 'main'
    show-status-pills = true
    show-date = true

[mode.main.binding]
